module.exports = {
    siteMetadata: {
        title: `Welcome`,
        titleTemplate: `nrs.`,
        description: `Full-Stack Developer specialized in the Front-End.`,
        lang: `en`,
        author: {
            name: 'Narin Sundarabhaya',
            url: 'https://twitter.com/ricopella',
            email: 'nrs710@gmail.com',
            handle: `@ricopella`,
        },
        headerItems: [`home`, `portfolio`, `about me`, `skills`, `contact`],
        portfolioItems: [{
                alt: 'Portfolio - FanAI Inc.',
                description: 'Audience Monetization Platform. Built with TypeScript, React, Highcharts.',
                fileName: 'fanai.png',
                href: 'https://fanai.io',
                title: 'FanAI',
            },
            {
                alt: `Portfolio - Matt Denny's Ale House Restaurant`,
                description: `Portfolio - Matt Denny's Ale House Restaurant`,
                fileName: 'md.png',
                href: 'https://mattdennys.com',
                span: `Denny's`,
                title: 'Matt',
            },
            {
                alt: 'Portfolio - Base Roots Shop',
                description: 'A customized Shopify store for an e-commerce client.',
                fileName: 'br.png',
                href: 'https://baserootsshop.com',
                span: `Roots`,
                title: 'Base',
            },
            {
                alt: 'Portfolio - Patient Stack',
                description: 'Patient management system for general practice doctors.',
                fileName: 'Patientstack.png',
                href: 'https://patientstack.herokuapp.com/',
                span: `Stack`,
                title: 'Patient',
            },
            {
                alt: 'Portfolio - Reacting To The Times',
                description: 'A NY Times Scrapper built with React.',
                fileName: 'reacting.png',
                href: 'https://reacting-to-the-times.herokuapp.com/',
                span: `To The Times`,
                title: 'Reacting',
            },
            {
                alt: 'Portfolio - Splitzease',
                description: 'A React-Native mobile application for splitting bills.',
                fileName: 'splitzease.jpg',
                href: 'https://github.com/ricopella/splitzease',
                span: `Ease`,
                title: 'Splitz',
            },
            {
                alt: 'Portfolio - Nike Trivia',
                description: 'A Nike themed trivia game built with Vanilla JavaScript.',
                fileName: 'nike.png',
                href: 'https://codepen.io/Ricopella/full/KvMeza/',
                span: `Trivia`,
                title: 'Nike',
            },
            {
                alt: 'Portfolio - Metta Healing Arts and Wellness',
                description: 'A client site built with Squarespace.',
                fileName: 'meta.png',
                href: 'https://mettavt.com/',
                span: `Healing Arts and Wellness`,
                title: 'Metta',
            },
            {
                alt: 'Portfolio - A cup of hacker noon',
                description: 'A web scrapper built with Cherrio, Node, Express, and MongoDB.',
                fileName: 'hack.png',
                href: 'https://cup-of-hackernoon.herokuapp.com/#results',
                span: `Hacker Noon`,
                title: 'A Cup of',
            },
        ],
        terminalCommands: [{
                answer: '"Los Angeles, CA"',
                question: 'current_location',
            },
            {
                answer: 'nrs710@gmail.com',
                href: 'mailto:nrs710@gmail.com',
                question: 'contact_information',
            },
            {
                answer: '["Front-End Web Developer", "Freelancer", "Certified Scrum Master"]',
                question: 'roles',
            },
            {
                answer: '["Complex web-apps", "Data visualizations in the browser", "Small business websites", "Shopify customizations", "Mobile apps"]',
                question: 'types_of_work',
            },
            {
                answer: '["TypeScript", "React", "Highcharts", "PostCSS", "Jest/Enzyme"]',
                question: 'most_recent_tech_stack',
            },
            {
                answer: '["Turntablism", "Record Collecting", "Music Production", Olde English Bulldog owner", "Photography", "Boston Sports - Bruins, Red Sox, Patriots, Celtics", "Eating new places", "Coffee", "Tacos"]',
                question: 'interests || hobbies',
            },
        ],
    },
    plugins: [
        `gatsby-plugin-react-helmet`,
        {
            resolve: `gatsby-source-filesystem`,
            options: {
                name: `images`,
                path: `${__dirname}/src/images`,
            },
        },
        `gatsby-transformer-sharp`,
        `gatsby-plugin-sharp`,
        {
            resolve: `gatsby-plugin-manifest`,
            options: {
                name: `gatsby-starter-default`,
                short_name: `starter`,
                start_url: `/`,
                background_color: `#663399`,
                theme_color: `#663399`,
                display: `minimal-ui`,
                icon: `src/images/favicon.ico`, // This path is relative to the root of the site.
            },
        },
        'gatsby-plugin-offline',
        'gatsby-plugin-emotion',
        `gatsby-plugin-typescript`,
        `gatsby-plugin-scroll-reveal`,
    ],
}